### ISSUE TITLE
Opstellen functionaliteiten

### ISSUE THREAD

**Issue by LdeKoning** [TNOCS/TO2#17]
Vanuit informatiebehoefte functionaliteiten bepalen (Vb ik wil als gebruiker dit en dit weten)

**Comment by LdeKoning** [comment]
Opzet van functionaliteiten gemaakt ter voorbereiding van workshop 1. Tijdens workshop vindt een selectie plaats van de functionaliteiten.

**Comment by jrest** [comment]
Albert en ik hebben vanuit de interviews een presentatie en workflow met high-level werkprocessen gemaakt.
