### ISSUE TITLE
Toestemming verkrijgen voor gebruik van 3Di-model "Kockengen"

### ISSUE THREAD

**Issue by janverkade** [TNOCS/TO2#25]

**Comment by janverkade** [comment]
Afspraak gemaakt voor di02jun

**Comment by janverkade** [comment]
Model is eigendom van HDSR (Hoogheemraadschap De Stichtse Rijnlanden). Crisiscoördinator ziet casus wel zitten. Binnenkort verder praten.

**Comment by ChristiaanHaro** [comment]
Laten ze zitten
