### ISSUE TITLE
Forensische database aanleggen

### ISSUE THREAD

**Issue by ruudpeters** [TNOCS/TO2#40]

**Comment by erikvullings** [comment]
- Wat versta jij hier precies onder? Van vorige incidenten, of van chemische stoffen?
- Moet die ook gevisualiseerd worden in de web omgeving?
- Wil je die delen met partners of open source?

**Comment by ruudpeters** [comment]
Hi Erik,

Hoef niets mee te doen. Het is een specifieke database van chemische stoffen die in andere databases zijn aangemerkt als “forensisch”. Is alleen van belang voor de identificatieprocedure bij de chemische laboratorium analyse. Hij hoeft niet te worden gedeeld met anderen.

Groeten,

Ruud

Ruud Peters
Senior Scientist

RIKILT- Institute of Food Safety, Wageningen UR
Business Unit Contaminants & Toxins
P.O. Box 230, 6700 AE, Wageningen, The Netherlands
Akkermaalsbos 2, 6708 PD, Wageningen, The Netherlands
Tel.      +31 (0)317 48 63 48 (mobile +31 (0)317 48 06 71)
Fax.     +31 (0)317 41 77 17
E-mail   ruudj.peters@wur.nlmailto:ruudj.peters@wur.nl
Internet www.rikilt.wur.nl<../../../../vermu005/Application%20Data/Microsoft/Signatures/www.rikilt.wur.nl>
