### ISSUE TITLE
Onzekerheidsvisualisatie

### ISSUE THREAD

**Issue by jgmdejong** [TNOCS/TO2#42]
Op basis van de informatiebehoefte de mogelijke visualisatie bepalen (inclusief onzekerheid van informatie presenteren)

**Comment by erikvullings** [comment]
Jan Verkade had hier ook al ideeën over wat betreft de waterstand: Bepaal de minimale afstand over alle 50 voorspellingen. Dat gedeelte loopt zeker onder. Daarnaast kun je ook een gebied bepalen dat in 90% van de scenario's onderloopt. Enige nadeel van beide scenario's is dat beide versies geen realistisch overstromingsbeeld opleveren.

Alternatief is dat we een scenario zoeken dat de grootste overeenkomst heeft met deze scenario's.
