### ISSUE TITLE
Opzetten plan voor meten mobiele veldapparatuur

### ISSUE THREAD

**Issue by ChristiaanHaro** [TNOCS/TO2#46]

**Comment by ruudpeters** [comment]
IN TE VULLEN DOOR TNO RIJSWIJK. 

O.a.: 1. Ondergrens van wat nog aangetoond kan worden. 2. Wat is de zekerheid van de identificatie. 3. Bruikbaarheid data voor laboratorium (wat en hoe).

Datum gereed: 29/6/2015
